name = "container-registry"
main = "src/index.ts"
compatibility_date = "2023-02-23"

[[r2_buckets]]
binding = "dataBucket"
bucket_name = "docker-registry"
preview_bucket_name = "docker-registry-preview"
